### ISSUE TITLE
batch runs

### ISSUE THREAD

**Issue by xubaqian** [avadhpatel/marss#60]
After simulating bzip in ubuntu-natty.qcow2 successfully, I try to run it in batch mode. Checkpoint has been created for bzip, but the command `./util/run_bench.py -d run bzip`
outputs the following message and halted.
`Reading config file /home/xqz/link/marss/util/util.cfg`
`Checkpoints: ['bzip']`
`simconfig: -logfile %(out_dir)s/%(bench)s.log`
`-stats %(out_dir)s/%(bench)s.yml`
`-machine xqz`
`%(default_simconfig)s`
`Total run configurations: 1`
`1 parallel simulation instances will be run.`
`All files will be saved in: run`
`Checkpoint bzip`
`All Threads are started`
`simconfig: -logfile /home/xqz/link/marss/run/bzip.log`
`-stats /home/xqz/link/marss/run/bzip.yml`
`-machine xqz`
`-kill-after-run -quiet`
`Config file written`
`Starting Checkpoint: bzip`
`Command:  /home/xqz/link/marss/qemu/qemu-system-x86_64 -m 4G -serial pty -nographic -drive cache=unsafe,file=/home/xqz/link/marss/myfile/ubuntu-natty.qcow2 -simconfig /home/xqz/link/marss/run/bzip.simcfg -loadvm bzip  -snapshot`
`char device redirected to /dev/pts/0`

`^CWriting to output file completed`
`Writing to stdout completed`
`Traceback (most recent call last):`
 ` File "./util/run_bench.py", line 420, in <module>`
`    th.join()`
 ` File "/usr/lib/python2.7/threading.py", line 940, in join`
  `  self.__block.wait()`
  `File "/usr/lib/python2.7/threading.py", line 340, in wait`
 `   waiter.acquire()`
`KeyboardInterrupt`

Did I miss anything?

**Comment by xubaqian** [comment]
just add  `-run` in `default_simconfig` ....
